### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by nhatfield** [haproxytech/vmware-haproxy#28]
Where can I find better documentation? Im having a hard time understanding how to get an ova to install in my vsphere content library. Can you point me in the right direction? 

From the vsphere docs they say to download an ova file from here.... but i dont see any ova files in this repo, nor do I see it in the release. Where, how, can I get the ova file?

**Comment by brakthehack** [comment]
Hey, thanks for trying out the product! You can find the list of available versions for download in the [README](https://github.com/haproxytech/vmware-haproxy) under the `Downloads` section. You can also locate downloads on the [releases page](https://github.com/haproxytech/vmware-haproxy/releases). You'll want to import the ova linked at the version you want to install to your content library through the content library import wizard.

Note that if your vCenter doesn't trust the `haproxy.com` domain, you'll likely want to perform a manual import where you download the image from the CDN and import it manually.

Let me know if this helps!

**Comment by nhatfield** [comment]
Wow, I feel terrible... I did not realize that the version itself is actually the link... I was looking at the hash, and the version next to it and looking for another "thing" to click to actually download. Thanks for the help, I think I can move forward on my install now =)

**Comment by brakthehack** [comment]
Sounds good. Thanks again for trying it out and feel free to report any additional issues!
